version: "3"

services: 
    
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
      container_name: elasticsearch
      environment:
        - node.name=elasticsearch
        - cluster.name=es-docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - http.cors.enabled=true
        - http.cors.allow-origin="*"
        - discovery.type=single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - elasticsearch_data:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
      networks: 
          - observability

    app:
      build: .
      container_name: app
      entrypoint: dockerize -wait tcp://postgres:5432 -timeout 20s ./docker/entrypoint.sh
      volumes: 
        - ./api_laravel:/var/www
      networks: 
        - observability

    nginx:
      build: ./docker/nginx
      container_name: nginx
      restart: always
      tty: true
      ports: 
        - "8080:80"
      volumes: 
        - ./api_laravel:/var/www
      networks: 
        - observability
      depends_on: 
        - app
    
    postgres:
      image: postgres:13.3-alpine
      container_name: postgres
      environment:
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_PASSWORD: "admin10"
        POSTGRES_DB: noticias
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - observability
  
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: "mario.galvao@gmail.com.br"
        PGADMIN_DEFAULT_PASSWORD: "admin10"
      ports:
        - "16543:80"
      depends_on:
        - postgres
      networks:
        - observability
  
    kibana:
      image: docker.elastic.co/kibana/kibana:7.13.0
      container_name: kibana
      ports:
        - 5601:5601
      environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
        ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      networks: 
        - observability
  
networks: 
  observability:
      external: true

volumes:
  postgres_data:
  elasticsearch_data: