version: "3"

services: 
    
    app_indexacao:
      build: .
      container_name: app_indexacao
      entrypoint: dockerize ./docker/entrypoint.sh
      volumes: 
        - .:/var/www
      networks: 
        - observability

    nginx_indexacao:
      build: ./docker/nginx
      container_name: nginx_indexacao
      restart: always
      tty: true
      ports: 
        - "8081:80"
      volumes: 
        - .:/var/www
      networks: 
        - observability
      depends_on: 
        - app_indexacao
   
networks: 
  observability:
      external: true
